spring: #前后端日期格式统一
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: always
  #servlet配置
  servlet:
    #上传文件设置
    multipart:
      #最大接收20MB
      max-file-size: 20MB
      #最大请求20MB
      max-request-size: 20MB
  #语言配置
  messages:
    #编码
    encoding: UTF-8
    #默认名称
    basename: i18n.messages
  mvc:
    #打印请求细节
    log-request-details: true
    #跨域配置
    cors:
      #路径映射
      path-mapping: /**
      #允许的来源
      allowed-origins:
        - '*'
      #允许的header
      allowed-headers:
        - '*'
      #允许的请求方法
      allowed-methods:
        - POST
        - GET
        - PUT
        - OPTIONS
        - DELETE
        - HEADER
      #开启验证 如果开启的话allowed-origins不能为*
      allowed-credentials: false
      max-age: 3600

    #拦截器配置
    interceptor:
      statistic-include:
        - /**
      statistic-exclude:
      cors-include:
        - /**
      cors-exclude:
      #access 放行url
      access-exclude:
        - /auth/login
        - /auth/register
        - /auth/refreshToken
        - /mail/sendAuthMail
        - /error
      #access 拦截url
      access-include:
        - /**
      #refesh 拦截url
      refresh-include:
        - /auth/refreshToken
      #refresh 放行url
      refresh-exclude:
        - /**


#服务器
server:
  #工作端口
  port: 8080
  #容器
  tomcat:
    #url编码
    uri-encoding: utf-8
  #错误重定向URL
  error:
    path: /error

  servlet:
    #默认容器路径/api开头
    context-path: /api
