spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lite_blog?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Hongkong&allowMultiQueries=true
    username: root
    password: wyh246859
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  redis:
    port: 6379
    host: localhost
    password: wyh246859
    lettuce: #默认使用lettuce
      pool:
        max-active: 100 # 最大连接数
        max-idle: 20 # 最大空闲连接
        min-idle: 5 #最小空闲连接
        max-wait: 12000 #连接等待时间
  devtools:
    restart:
      enabled: true

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml

server:
  port: 8088
  tomcat:
    uri-encoding: utf-8

logging:
  level:
    com.liteweb: debug
    web: debug
